### ISSUE TITLE
Cannot import Extractor

### ISSUE THREAD

**Issue by kuroboshi** [rahoulrdhopade/Sophos_Graylog_Extractor#1]
Hello,

I have this message when i try to import the json :

> Could not import content pack
Error importing content pack, please ensure it is a valid JSON file. Check your Graylog logs for more information.<br /><small>Unable to map property extractors. Known properties include: entities, rev, summary, vendor, inputs, lookup_tables, name, requires, url, outputs, streams, lookup_data_adapters, lookup_caches, _id, grok_patterns, description, category, dashboards, parameters, v, id</small>
![Error Import Extraxtor](https://github.com/rahoulrdhopade/Sophos_Graylog_Extractor/assets/22149432/acb7ba4b-a565-446f-976c-f3dd55ad9d63)

Graylog 5.2.4 on ubuntu 22.04

**Comment by bmelim** [comment]
you need to import it in the input extractors, paste the JSON content into the Import field.

**Comment by kuroboshi** [comment]
Thanks @bmelim  it's working but now i have a issue when Graylog extract all numbers such as rule_id or ip_adress or src_ip

Exemple : dst_ip=8.8.8.8
![image](https://github.com/rahoulrdhopade/Sophos_Graylog_Extractor/assets/22149432/9c8e141e-4bbe-47bc-b462-bc5ded3ee942)


It's work with another pattern :
![image](https://github.com/rahoulrdhopade/Sophos_Graylog_Extractor/assets/22149432/1188ca95-4bf4-4c0b-83bf-7e753e4a3650)
